### ISSUE TITLE
Suggestion: Relative path version of NodePath

### ISSUE THREAD

**Issue by Salvakiya** [eumario/GodotSharpExtras#1]
It would be neat to have a version of NodePath that let you get a relative path.

Issue:
currently if you have a scene which is instanced in a parent scene and you try using NodePath inside the instanced scene it will not work.

Suggest:
Adding the ability for relative NodePaths

Alternatively:
it would also be helpful if there was a way to find a node within the scene with a unique name. (relative to the instanced scene). Maybe this could be done by looking for the node name in the tscn file itself. This would mean you would only have to give the cs file the unique name instead of the path to the node.

**Comment by eumario** [comment]
I am unable to re-produce your error, could you provide a sample where the issue presents itself?

**Comment by eumario** [comment]
No response on this bug, and not able to reproduce, closing out.
